### ISSUE TITLE
Bidirectional arrows not displayed

### ISSUE THREAD

**Issue by DrQz** [mstefaniuk/graphviz.it#12]
![screen shot 2017-01-04 at 10 05 34 am](https://cloud.githubusercontent.com/assets/3886331/21653334/6b464d22-d265-11e6-8865-9c2d77a3a5a9.png)

**Comment by mstefaniuk** [comment]
Fix on the way.

**Comment by mstefaniuk** [comment]
Fixed in renderer version 0.9.22.
