### ISSUE TITLE
Text overflow

### ISSUE THREAD

**Issue by no-gravity** [mstefaniuk/graphviz.it#14]
Sometimes the text overflows the bounding box. Example:
```
digraph {
  node  [shape = record];
  "thistextoverflowstheboundingbox"
}
```

Renders like this here:
![overflow](https://cloud.githubusercontent.com/assets/2785829/21744041/cbeaeb1e-d50e-11e6-82eb-065701d6527c.png)

PS: Thank you for fixing the last issue so quick. This is a very interesting project.

**Comment by mstefaniuk** [comment]
I cannot reproduce it. It works on any browser on macOS. I suppose it is a local font issue (SVG generated uses locally installed). Could you confirm if it recreates on http://mdaines.github.io/viz.js/ ?

**Comment by no-gravity** [comment]
I see the overflow in Firefox 50.1.0 on Linux. Chromium renders it correctly.
On http://mdaines.github.io/viz.js/ both browsers render it correctly.

**Comment by mstefaniuk** [comment]
Could you attach PNG generated on the page (using top right button option _Store PNG on disk_) in both browsers? I want to verify if it is font size or font variant issue.

**Comment by no-gravity** [comment]
That does not work in Firefox. The event handler of the click on "#savePNGonDisk a" executes normally, but the img.onload function is never called. So no save dialog appears.

In Chromium, it works as expected.

**Comment by mstefaniuk** [comment]
I confirm it is not working on Firefox also on Windows. I have suspicion on that topic.

**Comment by mstefaniuk** [comment]
Site has been upgraded and generating PNG version should work now. Please attach comparable versions of problematic diagram.

**Comment by no-gravity** [comment]
Here we go:

Firefox:
![firefox](https://cloud.githubusercontent.com/assets/2785829/21826070/7033cc8a-d786-11e6-90c5-da4d989ab496.png)

Chromium:
![chromium](https://cloud.githubusercontent.com/assets/2785829/21826071/734c3c36-d786-11e6-9a28-aea3d35313bc.png)

**Comment by mstefaniuk** [comment]
Thanks, it looks as a matter of size not a font face.

**Comment by mstefaniuk** [comment]
I cannot reproduce that. I've checked on old FF (45) on SauceLabs. Could you also compare, using dom inspector, what size is attribute font size in both cases and what is actual calculated size?

**Comment by no-gravity** [comment]
SauceLabs does not have Linux support I guess? You can check on crossbrowsertesting.com. When chosing Ubuntu+Firefox, I get the textoverflow on crossbrowsertesting too.

The html is exactly the same in both browsers:
<div id="graph"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 212.2 45" height="45pt" width="212.2pt"><style type="text/css">.dashed {stroke-dasharray: 5,5} .dotted {stroke-dasharray: 1,5} .overlay {fill: none; pointer-events: all}</style><g><g transform="translate(4,41)scale(1,1)"><polygon stroke="#fffffe" stroke-opacity="0" fill="#ffffff" points="-4,4 -4,-45 212.2,-45 212.2,4"></polygon><g class="node" style="opacity: 1;"><title>thistextoverflowstheboundingbox</title><path stroke="#000000" fill="none" d="M 0,-0.5 L 0,-36.5,204.2,-36.5,204.2,-0.5 Z"></path><text font-family="'Times-Roman',serif" font-size="14" fill="#000000" text-anchor="middle" y="-14.3" x="102.1">thistextoverflowstheboundingbox</text></g></g></g></svg></div>

The above html is enough to reproduce the problem. It has overflow in FF and no overflow in Chromium. So further investigation should be possible with simple page rendering via browsershots.org or alike.

**Comment by mstefaniuk** [comment]
I'm not expecting huge differences in source itself but rather in actual calculated size. There is no unit attached and maybe Linux FF assumes different pixel size so different ratio is used.

Sauce has browsers on Linux but very old ones.

**Comment by no-gravity** [comment]
Both browsers assign a computed size of 14px to the text. 

I see the overflow on Ubuntu 15.04 / Firefox 44 at 1024x768 on CBT.

The font size changes a lot when changing the font family. For example with "arial" it easily fits into the bounding box. I also tried two web fonts (Open Sans and Roboto) and both cause the overflow to happen. To different degrees though.

**Comment by magjac** [comment]
I also get overflow when pasting the DOT source below to http://graphviz.it (Firefox 48.0 on Ubuntu 14.04.5 LTS).

Graphviz itself generates an ok PNG:
![sofia](https://cloud.githubusercontent.com/assets/6350376/23857535/f3e1292c-07fd-11e7-870f-652228aed4ed.png)

Saved PNG from graphviz.it:
![diagram](https://cloud.githubusercontent.com/assets/6350376/23857710/73fdd7fe-07fe-11e7-93d3-c6ebd7fd62c9.png)

DOT source:

// Dependencies for [u'SAND-34', u'SAND-30', u'SAND-29', u'SAND-28', u'SAND-26', u'SAND-25', u'SAND-24']
digraph {
	graph [fontsize=20.0 labelloc=t rankdir=BT tooltip="Drag here to pan"]
	node [fontname="Liberation Sans" fontsize=14 margin=0 shape=box style=filled tooltip="Click to go to \N in Jira"]
		"SAND-28" [label=< <TABLE ALIGN="LEFT" BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="2"> <TR><TD COLSPAN="2" BALIGN="LEFT" ALIGN="LEFT" >The Jacobssons are de-<BR/>stroying a sand<BR/>castle</TD></TR><TR><TD ALIGN="LEFT" BALIGN="LEFT" >Sofia</TD><TD ALIGN="RIGHT" VALIGN="BOTTOM">SAND-28</TD></TR> </TABLE> > URL="https://netinsight.atlassian.net/browse/SAND-28" color="#000000" fillcolor="#4a6785" fontcolor="#ffffff" shape=plaintext style=filled]
			"SAND-28" -> "SAND-30" [tooltip="There is no sand castle now... (SAND-30)
&#x2b06;
The Jacobssons are destroying a sand castle (SAND-28)"]
			"SAND-29" -> "SAND-28" [tooltip="The Jacobssons are destroying a sand castle (SAND-28)
&#x2b06;
The sand castle is complete! (SAND-29)"]
		"SAND-29" [label=< <TABLE ALIGN="LEFT" BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="2"> <TR><TD COLSPAN="2" BALIGN="LEFT" ALIGN="LEFT" >The sand castle is com-<BR/>plete!</TD></TR><TR><TD ALIGN="LEFT" BALIGN="LEFT" >Sofia</TD><TD ALIGN="RIGHT" VALIGN="BOTTOM">SAND-29</TD></TR> </TABLE> > URL="https://netinsight.atlassian.net/browse/SAND-29" color="#000000" fillcolor="#4a6785" fontcolor="#ffffff" shape=plaintext style=filled]
			"SAND-29" -> "SAND-28" [tooltip="The Jacobssons are destroying a sand castle (SAND-28)
&#x2b06;
The sand castle is complete! (SAND-29)"]
			"SAND-29" -> "SAND-30" [tooltip="There is no sand castle now... (SAND-30)
&#x2b06;
The sand castle is complete! (SAND-29)"]
			"SAND-26" -> "SAND-29" [tooltip="The sand castle is complete! (SAND-29)
&#x2b06;
The Jacobssons are building a sand castle (SAND-26)"]
			"SAND-34" -> "SAND-29" [tooltip="The sand castle is complete! (SAND-29)
&#x2b06;
? (SAND-34)"]
		"SAND-34" [label="?" URL="https://netinsight.atlassian.net/browse/SAND-34" color="#000000" fillcolor="#d04437" fontcolor="#ffffff" shape=circle style=filled]
			"SAND-34" -> "SAND-29" [tooltip="The sand castle is complete! (SAND-29)
&#x2b06;
? (SAND-34)"]
		"SAND-26" [label=< <TABLE ALIGN="LEFT" BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="2"> <TR><TD COLSPAN="2" BALIGN="LEFT" ALIGN="LEFT" >The Jacobssons are build-<BR/>ing a sand castle</TD></TR><TR><TD ALIGN="LEFT" BALIGN="LEFT" >Sofia</TD><TD ALIGN="RIGHT" VALIGN="BOTTOM">SAND-26</TD></TR> </TABLE> > URL="https://netinsight.atlassian.net/browse/SAND-26" color="#000000" fillcolor="#4a6785" fontcolor="#ffffff" shape=plaintext style=filled]
			"SAND-26" -> "SAND-29" [tooltip="The sand castle is complete! (SAND-29)
&#x2b06;
The Jacobssons are building a sand castle (SAND-26)"]
			"SAND-24" -> "SAND-26" [tooltip="The Jacobssons are building a sand castle (SAND-26)
&#x2b06;
Papsi plays in the Sandbox (SAND-24)"]
			"SAND-25" -> "SAND-26" [tooltip="The Jacobssons are building a sand castle (SAND-26)
&#x2b06;
Sofia plays in the Sandbox (SAND-25)"]
		"SAND-30" [label=< <TABLE ALIGN="LEFT" BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="2"> <TR><TD COLSPAN="2" BALIGN="LEFT" ALIGN="LEFT" >There is no sand castle<BR/>now...</TD></TR><TR><TD ALIGN="LEFT" BALIGN="LEFT" >Sofia</TD><TD ALIGN="RIGHT" VALIGN="BOTTOM">SAND-30</TD></TR> </TABLE> > URL="https://netinsight.atlassian.net/browse/SAND-30" color="#000000" fillcolor="#4a6785" fontcolor="#ffffff" shape=plaintext style=filled]
			"SAND-28" -> "SAND-30" [tooltip="There is no sand castle now... (SAND-30)
&#x2b06;
The Jacobssons are destroying a sand castle (SAND-28)"]
			"SAND-29" -> "SAND-30" [tooltip="There is no sand castle now... (SAND-30)
&#x2b06;
The sand castle is complete! (SAND-29)"]
		"SAND-24" [label=< <TABLE ALIGN="LEFT" BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="2"> <TR><TD COLSPAN="2" BALIGN="LEFT" ALIGN="LEFT" >Papsi plays in the Sand-<BR/>box</TD></TR><TR><TD ALIGN="LEFT" BALIGN="LEFT" >Sofia</TD><TD ALIGN="RIGHT" VALIGN="BOTTOM">SAND-24</TD></TR> </TABLE> > URL="https://netinsight.atlassian.net/browse/SAND-24" color="#000000" fillcolor="#f6c342" fontcolor="#000000" shape=plaintext style=filled]
			"SAND-24" -> "SAND-26" [tooltip="The Jacobssons are building a sand castle (SAND-26)
&#x2b06;
Papsi plays in the Sandbox (SAND-24)"]
		"SAND-25" [label=< <TABLE ALIGN="LEFT" BORDER="0" CELLBORDER="1" CELLSPACING="0" CELLPADDING="2"> <TR><TD COLSPAN="2" BALIGN="LEFT" ALIGN="LEFT" >Sofia plays in the Sand-<BR/>box</TD></TR><TR><TD ALIGN="LEFT" BALIGN="LEFT" >Sofia</TD><TD ALIGN="RIGHT" VALIGN="BOTTOM">SAND-25</TD></TR> </TABLE> > URL="https://netinsight.atlassian.net/browse/SAND-25" color="#000000" fillcolor="#f6c342" fontcolor="#000000" shape=plaintext style=filled]
			"SAND-25" -> "SAND-26" [tooltip="The Jacobssons are building a sand castle (SAND-26)
&#x2b06;
Sofia plays in the Sandbox (SAND-25)"]
}

**Comment by mstefaniuk** [comment]
I've found some text differences between Graphviz versions. Current version used on the page is quite outdated so maybe it will fix it. Stay tuned.

**Comment by magjac** [comment]
It doesn't seem to be the text that is the problem. Attached is a screenshot from Firefox 48.0 on Ubuntu 14.04 LTS. The top graph is generated with graph-viz-d3-js and the bottom graph with dot - graphviz version 2.36.0 (20140111.2315). It shows that it is the box that is too small

![screenshot from 2017-04-04 13 05 58](https://cloud.githubusercontent.com/assets/6350376/24653970/3c5f5d86-1938-11e7-9be1-237f1574b9ce.png)

**Comment by magjac** [comment]
It seems that the problem occurs already in the xdot. Attached are xdot outputs from two versions of graphviz and one from graph-viz-d3-js by logging the xdot at this line https://github.com/mstefaniuk/graph-viz-d3-js/blob/master/src/js/transformer.js#L6

[tmp-graphviz-2.38.0-graph-viz-d3-js-bug.xdot.txt](https://github.com/mstefaniuk/graphviz.it/files/892909/tmp-graphviz-2.38.0-graph-viz-d3-js-bug.xdot.txt)
[graph-viz-d3-js-bug.xdot.txt](https://github.com/mstefaniuk/graphviz.it/files/892907/graph-viz-d3-js-bug.xdot.txt)
[tmp-graphviz-2.36.0-graph-viz-d3-js-bug.xdot.txt](https://github.com/mstefaniuk/graphviz.it/files/892908/tmp-graphviz-2.36.0-graph-viz-d3-js-bug.xdot.txt)

> grep width *.txt
graph-viz-d3-js-bug.xdot.txt:		width=2.4167];
tmp-graphviz-2.36.0-graph-viz-d3-js-bug.xdot.txt:		width=2.7222];
tmp-graphviz-2.38.0-graph-viz-d3-js-bug.xdot.txt:		width=2.7083];
> grep height *.txt
graph-viz-d3-js-bug.xdot.txt:		height=0.51389,
tmp-graphviz-2.36.0-graph-viz-d3-js-bug.xdot.txt:		height=0.51389,
tmp-graphviz-2.38.0-graph-viz-d3-js-bug.xdot.txt:		height=0.5,

graph-viz-d3-js uses viz.js version 1.5.1 which in turn uses graphviz 2.38.0 (same as one of the above).

This indicates that there seems to be something wrong with the width in viz.js version 1.5.1 or in the way it is used.

**Comment by mstefaniuk** [comment]
Xdot output is generated directly from `viz.js` but I assume it can depend on system installed fonts. Main issue is that it is hard to reproduce so hard to fix it on my machine. Maybe upgrading will help.

**Comment by magjac** [comment]
As I said, I don't think it's a problem with the text (font). It has the correct size. It's the text boxes that have a too small width.

Why is it hard to reproduce? Just paste [bug.dot.txt](https://github.com/mstefaniuk/graphviz.it/files/895225/bug.dot.txt) into http://graphviz.it. The problem is present with Firefox and Chrome, both on Windows and on Ubuntu 14.04.

**Comment by magjac** [comment]
I upgraded to viz.js version 1.7.1. It didn't help.

I also tested to use viz.js directly in my project by calling Viz(dotSrc) and it didn't help either. I guess this means that graph-viz-d3-js is no longer a suspect and this issue is invalid.

I will open a new issue on viz.js.

**Comment by magjac** [comment]
Filed issue https://github.com/mdaines/viz.js/issues/81
