### ISSUE TITLE
Locally installed graphviz.it gives error: .../graphviz.it/dist/config.js Not Found

### ISSUE THREAD

**Issue by magjac** [mstefaniuk/graphviz.it#18]
Trying to set up graphviz.it locally in order to start experimenting with graph-viz-d3-js

I successfully did:
 
git clone https://github.com/mstefaniuk/graphviz.it.git
cd graphviz.it/
bower install
npm install
grunt

When opening the .../graphviz.it/dist/index.html page with Firefox/52.0.1, I get:

GET http://madrox.netinsight.se:8084/graphviz.it-luser/graphviz.it/dist/config.js Not Found
...
Error: Script error for: config http://requirejs.org/docs/errors.html#scripterror  require.js:166:17
...
TypeError: asm.js type error: incompatible type for argument 5: (f64 here vs. i32 before)  layout-worker.js:3230:60

Is this config.js file missing in the repo or am I doing something wrong?

**Comment by magjac** [comment]
Full log from Firefox console:
[graphviz.it_bug.txt](https://github.com/mstefaniuk/graphviz.it/files/852424/graphviz.it_bug.txt)

**Comment by mstefaniuk** [comment]
To start locally you need `npm install` and `grunt build development start`. If you want to use it on your own I would suggest to use [rendering component](mstefaniuk/graph-viz-d3-js) directly.

**Comment by magjac** [comment]
Thanks a lot. After some struggling with a too old version of nodejs, I got it working :-8.

Thanks for your suggestion. That's exactly what I'm planning to do, but since I'm new to nodejs, npm, bower, require.js, grunt and d3, I thought I'd get something up and running out-of-the box so I know I've gotten all that stuff right before introducing my own problems.

Again, thanks :-)

Now the fun begins...
