### ISSUE TITLE
Support for 'id' attribute

### ISSUE THREAD

**Issue by kenseehart** [mstefaniuk/graphviz.it#19]
foo_node **[id=foo_node_id]**

should render as  

<g class="node" **id="foo_node_id"**> ... <\/g>

Motivation: This opens up unlimited possibilities for real-time DOM customization in js.
The 'id' attribute is in the dot standard: http://www.graphviz.org/doc/info/attrs.html#d:id

**Comment by mstefaniuk** [comment]
@kenseehart Please check if new version of graph-viz-d3-js rendering component is working as you expected.

**Comment by kenseehart** [comment]
Apologies for the rather belated reply.... Thank you, works great!
